name: イシュー
description: "インシデントを登録します"
title: "[sgs] "
labels: ["sgs"]
assignees: 
  - zummyJP
body:
  - type: markdown
    attributes: 
      value: "インシデント内容を正確に登録ください"
  - type: dropdown
    id: type
    attributes:
      label: 種別
      description: "description"
      options:
        - 不具合
        - 要望
        - 問い合わせ
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: ステータス
      description: "description"
      options:
        - 新規
        - 着手中
        - 修正完了
        - 修正確認完了
        - 差し戻し
        - 再現待ち
        - 見送り
        - 保留
        - 終了
    validations:
      required: true
  - type: checkboxes
    id: functions
    attributes:
      label: 機能
      description: "description"
      options:
        - label: 代理店選択
        - label: 申込
        - label: 受付・貸出
        - label: オールマイティ・事前決済
        - label: 呼出・マイページ
        - label: マスタ・売上集計
        - label: インフラ・その他
    validations:
      required: true
  - type: checkboxes
    id: users
    attributes:
      label: ユーザー
      description: "description"
      options:
        - label: 全ユーザー
        - label: 高鷲スノーパーク
        - label: ダイナランド
        - label: ホワイトピア高鷲
        - label: 明宝スキー場
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: 概要
      description: "description"
      value: |
        ### 現在の動作、発生した手順:

        ### 環境(デバイス, OS, ブラウザ):

        ### 期待する動作:

        ### その他:

    validations:
      required: true
  - type: dropdown
    id: urgency
    attributes:
      label: 緊急度
      description: "description"
      options:
        - 高 (当日中に対応)
        - 中 (週末までに対応)
        - 低 (順次対応)
    validations:
      required: true
  - type: dropdown
    id: importance
    attributes:
      label: 重要度
      description: "description"
      options:
        - 高 (営業に支障あり)
        - 中
        - 低 (軽微な問題)
    validations:
      required: true
  - type: textarea
    id: related
    attributes:
      label: 関連インシデント
      description: "description"
      value: |
        ### 関連インシデントのURL:

    validations:
      required: false
