name: イシュー
description: "インシデントを登録します"
title: "[sgs]"
labels: ["sgs"]
assignees: 
  - zummyJP
body:
  - type: markdown
    attributes: 
      value: "インシデント内容を正確に登録ください"
  - type: dropdown
    id: type
    attributes:
      label: issue種別
      description: "description"
      options:
        - 不具合 (Default)
        - 要望
        - 問い合わせ
    validations:
      required: true
