name: イシュー
description: "インシデントを登録します"
title: "[sgs]"
labels: ["sgs"]
assignees: 
  - zummyJP
body:
  - type: markdown
    attributes: 
      value: "インシデント内容を正確に登録ください"
  - type: dropdown
    id: type
    attributes:
      label: issue種別
      description: "description"
      options:
        - 不具合 (Default)
        - 要望
        - 問い合わせ
    validations:
      required: true
  - type: dropdown
    id: status
    attributes:
      label: ステータス
      description: "description"
      options:
        - 新規 (Default)
        - 着手中
        - 修正完了
        - 修正確認完了
        - 差し戻し
        - 再現待ち
        - 見送り
        - 保留
        - 終了
    validations:
      required: true

      label: 関連イシュー
      description: "description"
      value: |
### 関連イシューのURL:
    validations:
      required: false
