name: Datetime

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  job:
    name: datetime
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
      - name: Set current time as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_TIME=$(date +'%H:%M:%S')" >> $GITHUB_ENV
      - name: Show current date
        run: echo ${{ env.CURRENT_DATE }}
      - name: Show current time
        run: echo ${{ env.CURRENT_TIME }}
