name: Datetime

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  job:
    name: datetime
    runs-on: ubuntu-latest
    steps:
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d %H:%M:%S')"
      - name: Show current datetime
        run: echo ${{ env.CURRENT_DATETIME }}
